const IconNames = {
  Agenda: 'agenda',
  Bank: 'bank',
  Bar: 'bar',
  BrokenClouds: 'broken-clouds',
  ChevronDown: 'chevron-down',
  ChevronLeft: 'chevron-back',
  ChevronRight: 'chevron-right',
  Clear: 'clear',
  ClearSky: 'clear-sky',
  Cloud: 'cloud',
  Currency: 'currency',
  FewClouds: 'few-clouds',
  Globe: 'globe',
  Hamburger: 'hamburger',
  Home: 'home',
  Hotel: 'hotel',
  MedicalItem: 'medical-item',
  Mist: 'mist',
  Moli: 'moli',
  Phone: 'phone',
  Place: 'place',
  Rain: 'rain',
  Restaurant: 'restaurant',
  ScatteredClouds: 'scattered-clouds',
  Search: 'search',
  ShowerRain: 'shower-rain',
  Snow: 'snow',
  Target: 'target',
  Theater: 'theater',
  ThunderStorm: 'thunder-storm',
  Tree: 'tree'
};

export default IconNames;
